name: absher
description: A new Flutter project.

version: 0.0.04+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  dio: ^5.1.2
  dartz: ^0.10.1
  flutter_svg:
  carousel_slider: ^4.2.1
  overlay_support: ^2.1.0
  sms_autofill: ^2.3.0
  flutter_spinkit: ^5.2.0
  shimmer:
  package_info_plus: ^4.0.0
  dismissible_page: ^1.0.2
  extended_image: ^7.0.2
  lottie:
  video_player: ^2.6.1
  animations: ^2.0.7
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  custom_map_markers: ^0.0.2+1
  flutter_screenutil: ^5.7.0
  flutter_local_notifications: ^14.1.1
  percent_indicator: ^4.2.3
  card_swiper: ^2.0.4
  flutter_html:
  image_picker:
  url_launcher: ^6.1.11
  firebase_messaging:



dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  #  assets:
  #    - assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo-Medium.ttf
          weight: 500
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo-Bold.ttf
          weight: 700


